### ISSUE TITLE
Improve Interaction Network

### ISSUE THREAD

**Issue by sureshhewabi** [GeoDiver/GEODiver#63]
I guess it is better to have a label or description for colour code in Interaction Networks. Because a lot of people might confuse with what colour represent up-regulation down-regulation.  

- [ ] Add a Colour Code to distinguish between up- and down- regulation in the interaction networks

**Comment by IsmailM** [comment]
Isn't there one already a colour code key in the interaction networks?

If so, is it worth adding another on?

@Anisatu @MPriebe

**Comment by Anisatu** [comment]
Hi @IsmailM , sorry for the incredibly late reply. @sureshhewabi is right, there's nowhere on the actual interaction network that explicitly explains what the colour code represents (and the link to the kegg website doesn't really help). Also, now that I that I've just looked over the results page again, I'm also not that sure it's particularly obvious to potential users that clicking the graph button will mean that an interaction network will be shown.

But to solve this particular issue ( and issue #61 ), we could something similar to what we have in the advanced parameters, where there's a little information sign and a brief description of what the colour code represents.

**Comment by IsmailM** [comment]
@Anisatu 

I've added a tooltip to each of the graph icons further to your comment.

Looking at the current interaction networks (see image below), it seems they already have a key?

If you want I can put another one in (i.e. the same one) above each interaction network (even though I don't see the point of that)?

what do u suggest?

<img width="1197" alt="geodiver" src="https://cloud.githubusercontent.com/assets/5578375/20866623/4606e50c-ba29-11e6-8f54-b5194820e040.png">

**Comment by Anisatu** [comment]
Yeah, so my issue is that I actually don't think the existing key is clear enough. It doesn't actually explain what the -1 and 1 values indicate in this case, and the way they've colour coded it seems counterintuitive  (red is usually associated with negative numbers).

There's a chance that I'm just being pernickety though, I think we'll be ok with submitting the paper without changing the key.

**Comment by IsmailM** [comment]
Make sense. It's an easy fix - so might as well fix it if u think it will make a difference

So in your opinion, what should we replace the numbers (+1 and -1) in the key with?

**Comment by IsmailM** [comment]
Alternatively, it is possible to change the colours in Pathview (which is also very easy to change)...

BUT, this is the default, and so it would look odd to anyone seen images created by pathview before...


So what solution do u suggest?

**Comment by Anisatu** [comment]
I agree that it's probably best to use the same colour scheme, and the more I think about it, as long as the tool tip mentions that the each interaction network shows genes that have been up or downregulated, I think it'll be ok

**Comment by IsmailM** [comment]
Added a colour key to above each interaction network...

<img width="1469" alt="geodiver" src="https://cloud.githubusercontent.com/assets/5578375/20868730/5dd607ae-ba5a-11e6-813d-682d0334e329.png">

**Comment by Anisatu** [comment]
Looks good!
