### ISSUE TITLE
What files to download for GSE Analysis

### ISSUE THREAD

**Issue by IsmailM** [GeoDiver/GEODiver#72]
For GEO datasets, we currently download the soft.gz file, analyse it and then pass the downloaded file into the download_GEO.R script.

I have tried this for GSE, but am not sure what file to download.

Thus need to download all the different file types on NCBI for GSE and try them on the download_GEO.R script...

@Nazrath10R @sureshhewabi

**Comment by sureshhewabi** [comment]
Hi ismail, Look at this example. According to this, it is just .raw format
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE3541
see the supplementary section at the bottom of the page

**Comment by sureshhewabi** [comment]
In other words, we need to download all the raw files which starts its name with "GSE". That is my understanding.

**Comment by IsmailM** [comment]
Seems like we only need to download the matrix file...

Fixed in 085077c
