### ISSUE TITLE
Group Name consistency

### ISSUE THREAD

**Issue by Nazrath10R** [GeoDiver/GeoDiver#86]
it's group 1 and 2 in all plots (HeatMap, DGEA, PCA)
in Groups to select it's A and B

changing A and B to 1 and 2 is the easy fix

importing the actual 'name' from the groups into the plots, would be amazing.
if someone actually does use GeoDiver to produce their results and downloads the plots, the group names being on there would be so much nicer rather than 1 & 2 or A & B (especially if they have several plots in their paper etc.)

**Comment by IsmailM** [comment]
Fixed
