### ISSUE TITLE
Many GSE datasets fail to run

### ISSUE THREAD

**Issue by IsmailM** [GeoDiver/GeoDiver#88]
This is because of the following code: https://github.com/GeoDiver/GeoDiver/blob/master/RCore/download_GEO.R#L71-L89

```R
gset <- getGEO(argv$accession, GSEMatrix = TRUE, destdir=argv$geodbDir)

if (grepl('^GDS', argv$accession)) {
  eset           <- GDS2eSet(gset, do.log2 = FALSE)
  gene.names     <- as.character(gset@dataTable@table$IDENTIFIER)
  organism       <- as.character(Meta(gset)$sample_organism)
  gpl            <- getGEO(Meta(gset)$platform, destdir=argv$geodbDir)
  featureData    <- gpl@dataTable@table
} else if (grepl('^GSE', argv$accession)) {
  if (length(gset) > 1) idx <- grep(gset@annotation, attr(gse, "names")) else idx <- 1
  eset           <- gset[[idx]]
  gene.names     <- as.character(eset@featureData@data[, "Gene Symbol"])
  organism       <- as.character(eset@featureData@data[, "Species Scientific Name"][1])
  featureData    <- eset@featureData@data
}

X      <- exprs(eset) # Get Expression Data
pData       <- pData(eset)
rownames(X) <- gene.names
```

**Comment by IsmailM** [comment]
GSE61369 is an exemplar GEO data series that fails

**Comment by sureshhewabi** [comment]
by looking at both GSE51808(working) and GSE61369(not working) data, I realise that, GSE61369 does not contain expression information. it should be available at the end of the content. Both datasets are getting downloaded by getGEO() method, but GSE61369 fails when we try to extract some data from it. So my question is do we really need to consider such datasets?

**Comment by sureshhewabi** [comment]
<img width="672" alt="screen shot 2017-05-19 at 5 00 31 pm" src="https://cloud.githubusercontent.com/assets/5387193/26246122/1861eeee-3cb5-11e7-9ca4-9fe6ce0ce845.png">
<img width="947" alt="screen shot 2017-05-19 at 5 01 05 pm" src="https://cloud.githubusercontent.com/assets/5387193/26246123/19d4c59e-3cb5-11e7-9d26-adb092aa0c88.png">

**Comment by IsmailM** [comment]
Do the associated Matrix files contain this info?

**Comment by IsmailM** [comment]
The issue is that a large number of GSE files are failing because of this - I'll do a complete test on all GSE files this weekend.. 

As such we neeed to get this working :)
