### ISSUE TITLE
[Chrome] Cannot select alternative factor to analyze

### ISSUE THREAD

**Issue by julianstanley** [GeoDiver/GeoDiver#97]
![image](https://user-images.githubusercontent.com/22749289/31551984-31d08f30-b004-11e7-92bd-bdb5a38792b9.png)

The radio buttons to select different factors aren't working for me in Google Chrome.

**Comment by IsmailM** [comment]
Hey @julianstanley,

I've fixed the Radio button issue. It was an issue in one of the libraries that we are using.

However, there seems like that there is still an issue in parsing the GSE dataset that you have shown in the screenshot.

Specifically, there is no GeneSymbols column in the featureData object. In order to parse the datasets, I'm using the `gene_assignment` column. However, the values in this column can be quite long (because they contain multiple names for the same gene) as such this does cause some formatting issues... 

This is the featureData object for this GSE:

```R
  ..@ featureData      :Formal class 'AnnotatedDataFrame' [package "Biobase"] with 4 slots
  .. .. ..@ varMetadata      :'data.frame':	12 obs. of  3 variables:
  .. .. .. ..$ Column          : chr [1:12] "ID" "GB_LIST" "SPOT_ID" "seqname" ...
  .. .. .. ..$ Description     : Factor w/ 12 levels "Array design category of the transcript cluster",..: 12 4 6 2 7 10 8 9 11 5 ...
  .. .. .. ..$ labelDescription: chr [1:12] NA NA NA NA ...
  .. .. ..@ data             :'data.frame':	33297 obs. of  12 variables:
  .. .. .. ..$ ID             : chr [1:33297] "7892501" "7892502" "7892503" "7892504" ...
  .. .. .. ..$ GB_LIST        : Factor w/ 21975 levels "","AB593172,AF161351",..: 1 1 1 1 1 1 1 1 1 1 ...
  .. .. .. ..$ SPOT_ID        : Factor w/ 28689 levels "chr1:10003486-10045556",..: 28689 28689 28689 28689 28689 28689 28689 28689 28689 28689 ...
  .. .. .. ..$ seqname        : Factor w/ 37 levels "chr1","","---",..: 3 3 3 3 3 3 3 3 3 3 ...
  .. .. .. ..$ RANGE_GB       : Factor w/ 26 levels "NC_000001.10",..: 2 2 2 2 2 2 2 2 2 2 ...
  .. .. .. ..$ RANGE_STRAND   : Factor w/ 4 levels "+","","-","---": 4 4 4 4 4 4 4 4 4 4 ...
  .. .. .. ..$ RANGE_START    : chr [1:33297] "---" "---" "---" "---" ...
  .. .. .. ..$ RANGE_STOP     : chr [1:33297] "---" "---" "---" "---" ...
  .. .. .. ..$ total_probes   : int [1:33297] 4 4 4 4 4 4 4 4 4 4 ...
  .. .. .. ..$ gene_assignment: Factor w/ 24534 levels "---","AB593172 // SSU72 // SSU72 RNA polymerase II CTD phosphatase homolog (S. cerevisiae) // 1p36.33 // 29101",..: 1 1 1 1 1 1 1 1 1 1 ...
  .. .. .. ..$ mrna_assignment: Factor w/ 27303 levels "AB593172 // GenBank // Homo sapiens HP08716 mRNA, partial sequence, clone: HP08716-RBd88H07. // chr1 // 91 // 1"| __truncated__,..: 27013 6359 6359 6359 6359 6359 6359 6359 27013 6359 ...
  .. .. .. ..$ category       : Factor w/ 7 levels "main","","control->affx",..: 6 7 7 7 7 7 7 7 6 7 ...
```

**Comment by julianstanley** [comment]
Thank you for fixing the radio button problem! I have lots of datasets to throw in (and some of them have been throwing errors, some not) so I have numbers of unworking and working sets that I can post here later too, if that's helpful.

**Comment by IsmailM** [comment]
Hey @julianstanley,

No worries, Thanks for noticing that. Would really appreciate if you could create an issue for any failing datasets 👍  - it would help us in looking into the underlying issue...

If you have any other feedback or an idea on how things can be improved, feel free to give us a shout.
