### ISSUE TITLE
HTTPS Error

### ISSUE THREAD

**Issue by julianstanley** [GeoDiver/GeoDiver#99]
In Chrome, I get a "Your connection is not private" error when I visit GeoDiver. I think this is part of a new trend of browsers more heavily enforcing https (see: https://security.googleblog.com/2017/04/next-steps-toward-more-connection.html). 

Github doesn't directly support HTTPS for custom domain names

For my personal page, I fixed that problem by going through Cloudflare (https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b). It's free--took around 20 hours for everything to process, but setup was easy. Would recommend if you don't have something else in the queue.

**Comment by IsmailM** [comment]
Hey, @julianstanley,

Thanks for pointing this out.

We are currently hosted on a private server (and not github) and we are using a free [Let's Encrypt SSL](https://letsencrypt.org/) - which needs to be renewed every 3 months. We have a cron job that automatically attempts to renew the ssl certificate twice every day; however this seems to be broken.

As such, I've emailed the server admin to fix the cronjob in charge of automatically renewing the ssl. Hopefully it'll be fixed soon. 

PS. take a look at [Netlify](https://www.netlify.com/) for your personal website - it's better than the cloudflare solution + is also more secure (there is still a risk of a MITM attack with the way it needs to be set up with github)...

**Comment by IsmailM** [comment]
Hey,

This should now be fixed...

Let me know if you still face any issues.

Kind regards,
Ismail
